#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "s/server_name _;/server_name _;\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" 
sudo sed -i "s/return 404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/g" /etc/nginx/sites-available/default
sudo service nginx start
