#!/usr/bin/env bash
# Configures nginx server to respond to status code '404',
# returns a custom Error 404 page containing "Ceci n'est pas une page".

apt-get update
apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
sudo echo "Holberton School" > /etc/nginx/html/index.html #open file directly to edit contents. sudo vi /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html #open file directly to edit contents. sudo vi /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
